//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiTroWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.RoomInfoes = new HashSet<RoomInfo>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phoneNum { get; set; }
        public string email { get; set; }
        public string zaloNum { get; set; }
        public string FBlink { get; set; }
        public string file_name { get; set; }
        public string imagePath { get; set; }
        public string password { get; set; }
        public bool resetPass { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInfo> RoomInfoes { get; set; }
    }
}
