//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiTroWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string location { get; set; }
        public string image { get; set; }
        public string contactInfo { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public Nullable<int> topic_id { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
