//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiTroWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int id { get; set; }
        public string title { get; set; }
        public string companyInfo { get; set; }
        public string contactAddress { get; set; }
        public string contactEmail { get; set; }
        public string contactPhone { get; set; }
        public string socialFacebook { get; set; }
        public string socialTwitter { get; set; }
        public string socialLinkedIn { get; set; }
        public string socialYoutube { get; set; }
        public string copyrightInfo { get; set; }
        public string privacyPolicyLink { get; set; }
        public string termsOfServiceLink { get; set; }
        public string TermsOfUseLink { get; set; }
        public string TermsOfPostingLink { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    }
}
