//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiTroWebsite.Models
{
    using System;
    using System.Collections.Generic;
    //them xu ly not null
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class News
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Tiêu đề không được để trống.")]
        public string title { get; set; }
        public string file_name { get; set; }
        public string imagePath { get; set; }
        [Required(ErrorMessage = "Mô tả không được để trống.")]
        public string brief_description { get; set; }
        [Required(ErrorMessage = "Nội dung không được để trống.")]
        public string detail_description { get; set; }
        [Required(ErrorMessage = "Tác giả không được để trống.")]
        public string author { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public Nullable<int> newsTypeId { get; set; }
    
        public virtual NewsType NewsType { get; set; }
    }
}
