//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoiTroWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomImg
    {
        public long id { get; set; }
        public int postRoomId { get; set; }
        public string fileName { get; set; }
        public string folder { get; set; }
        public string serverFolder { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual RoomInfo RoomInfo { get; set; }
    }
}
